DM-27663: Update ts_observatory_control other packages to stop using Rotator application topic
lsst-ts/ts_observatory_control pull request #20
Opened 2020-12-11 22:17 UTC by tribeiro

Remove usage of deprecated rotator application topic in favor of rotation.
Remove pre-commit hook and add pre-commit configuration.
Add pytest-back.

2020-12-11 23:13 UTC, r-owen requested changes
I think I found one bug. Otherwise looks good. Thanks for making this change.

2020-12-11 23:13 UTC, r-owen commented on python/lsst/ts/observatory/control/maintel/mtcs.py
> +                rotator = await self.rem.mtrotator.tel_rotation.next(
Please consider `rotation` or `rotation_data` for the data. It is a better match to the telemetry topic name.

(In a unit test you use a completely different variable name for the same thing, which I complain about below).

2020-12-12 00:04 UTC, tribeiro commented on python/lsst/ts/observatory/control/mock/mtcs_mock.py
> +                position = self.controllers.mtrotator.tel_rotation.data.actualPosition
Sorry, not sure I understood this comment. Is it possible you are confusing `Controller` with `Remote`? `self.controllers.mtrotator` is a controller for `MTRotator`, this 

```
self.controllers.mtrotator.tel_rotation.data
```

will never return `None` right?

2020-12-12 00:10 UTC, tribeiro commented
I think I implemented all your comments, except for the one which I didn't understand.

2020-12-12 00:28 UTC, r-owen commented on python/lsst/ts/observatory/control/mock/mtcs_mock.py
> +                position = self.controllers.mtrotator.tel_rotation.data.actualPosition
You are right; I had missed that. A WriteTopic will always return a sample.

However, that sample will contain initialized values (which may not be realistic) until you have written it once. Is that safe here? If not then it's still worth some protection. A code comment would be appreciated in any case.

Note that WriteTopic has a property `has_data` which allows you to test if you have ever written data. So you could modify my incorrect suggestion with:
```
if not self.controllers.mtrotator.tel_rotation.has_data:
    # return or do something else intelligent
rotation = self.controllers.mtrotator.tel_rotation.data
rot_delta = ...
```
I suppose the fact that no data has been written will result in rot_delta = 0, which _might_ be fine. But I hope you will think about what seems best and add a code comment explaining.

2020-12-12 00:31 UTC, r-owen approved these changes
I replied to your one comment. I am happy to have you merge it once you have thought about that one a bit more.

2020-12-14 21:30 UTC, merged